files:
# addons/xpaas
# addons/xpaas/v3.10/xpaas-streams
- this: "addons/xpaas/v3.10/xpaas-streams/amq62-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/amq62-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/amq63-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/amq63-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/datagrid65-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/datagrid65-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/datagrid71-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/datagrid71-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/datagrid72-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/datagrid72-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/datavirt63-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/datavirt63-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/decisionserver62-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver62-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/decisionserver63-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver63-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/decisionserver64-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/decisionserver64-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/eap70-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/eap70-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/eap71-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/eap71-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/fis-image-streams.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/fis-image-streams.json"
- this: "addons/xpaas/v3.10/xpaas-streams/jws30-tomcat7-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/jws30-tomcat7-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/jws30-tomcat8-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/jws30-tomcat8-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/jws31-tomcat7-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/jws31-tomcat7-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/jws31-tomcat8-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/jws31-tomcat8-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/openjdk18-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/openjdk18-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/processserver63-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/processserver63-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/processserver64-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/processserver64-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/rhdm70-image-streams.yaml"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/rhdm70-image-streams.yaml"
- this: "addons/xpaas/v3.10/xpaas-streams/rhpam70-image-streams.yaml"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/rhpam70-image-streams.yaml"
- this: "addons/xpaas/v3.10/xpaas-streams/sso70-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/sso70-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/sso71-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/sso71-image-stream.json"
- this: "addons/xpaas/v3.10/xpaas-streams/sso72-image-stream.json"
  that: "https://raw.githubusercontent.com/openshift/openshift-ansible/release-3.10/roles/openshift_examples/files/examples/v3.10/xpaas-streams/sso72-image-stream.json"

